# Site settings
title: Of Being Honest
author: Becky Koleth
email: rebeccakoleth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A pursuit of honesty

# Build settings
markdown: kramdown
permalink: /:year-:month-:day/:title
paginate: 5

# Tale theme settings (if using as remote theme)
# remote_theme: chesterhow/tale

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
